version: 2
jobs:
    build:
        working_directory: /go/src/github.com/justbuchanan/stylize
        docker:
            - image: justbuchanan/docker-archlinux
        steps:
            # setup GOPATH
            - run: echo 'export GOPATH=/go' >> $BASH_ENV
            - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV

            - run: echo 'export CIRCLE_ARTIFACTS=/tmp/artifacts' >> $BASH_ENV
            - run: mkdir -p $CIRCLE_ARTIFACTS

            # install deps
            - run: pacman -Sy --noconfirm clang python-pip go git
            - run: pip install yapf
            - run: go get -u github.com/bazelbuild/buildtools/buildifier
            - run: go get -u github.com/justbuchanan/ci-status
            - run: go get golang.org/x/tools/cmd/cover
            - run: go get github.com/mattn/goveralls

            - checkout

            # setup git
            - run: git config --global user.email "ci@circle"
            - run: git config --global user.name "Circle Ci"

            # install stylize deps
            - run: go get -t ./...

            - run: ci-status --context build --description "go build" "go build"

            - run: ci-status --context checkstyle --description "run stylize" "./stylize --exclude_dirs=testdata --patch_output /tmp/artifacts/pretty.patch" || true

            - run: ci-status --context tests --description "go test" "go test -v -covermode=count -coverprofile=coverage.out"
            - run: ci-status -h --context coverage_upload --description "upload coverage with goveralls" "goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_REPO_TOKEN"

            - store_artifacts:
                path: /tmp/artifacts

workflows:
  version: 2
  all:
    jobs:
      - build
