version: 2
jobs:
    build:
        working_directory: /go/src/github.com/justbuchanan/stylize
        docker:
            - image: justbuchanan/docker-archlinux
        steps:
            # setup GOPATH
            - run: echo 'export GOPATH=/go' >> $BASH_ENV
            - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV

            # install system deps
            - run: pacman -Sy --noconfirm clang python-pip go git
            - run: pip install yapf
            - run: go get -u github.com/bazelbuild/buildtools/buildifier

            - run: mkdir -p /tmp/artifacts

            - checkout

            # setup git
            - run: git config --global user.email "ci@circle"
            - run: git config --global user.name "Circle Ci"

            # install stylize deps
            - run: go get -t ./...

            - run: go build
            - run: go test . -v | tee /tmp/artifacts/test.log 2>&1

            - store_artifacts:
                path: /tmp/artifacts

workflows:
  version: 2
  all:
    jobs:
      - build

# TODO: coveralls
# TODO: check code style of this repo
