version: 2
jobs:
    build:
        working_directory: /go/src/github.com/justbuchanan/stylize
        docker:
            - image: justbuchanan/docker-archlinux
        steps:
            # setup GOPATH
            - run: echo 'export GOPATH=/go' >> $BASH_ENV
            - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV

            - run: echo 'export CIRCLE_ARTIFACTS=/tmp/artifacts' >> $BASH_ENV
            - run: mkdir -p $CIRCLE_ARTIFACTS

            # install deps
            - run: pacman -Sy --noconfirm clang python-pip go git
            - run: pip install yapf
            - run: go get -u github.com/bazelbuild/buildtools/buildifier
            - run: go get -u github.com/justbuchanan/ci-status

            - checkout

            # setup git
            - run: git config --global user.email "ci@circle"
            - run: git config --global user.name "Circle Ci"

            # install stylize deps
            - run: go get -t ./...

            - run: ci-status --context tests --description "go test" "go test . -v"
            - run: ci-status --context build --description "go build" "go build"
            - run: ci-status --context checkstyle --description "run stylize" "./stylize --exclude_dirs=testdata --patch_file_out /tmp/artifacts/pretty.patch"

            - store_artifacts:
                path: /tmp/artifacts

workflows:
  version: 2
  all:
    jobs:
      - build

# TODO: coveralls
# TODO: check code style of this repo
