name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      
      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y black uncrustify

      - name: Install prettier
        run: npm install -g prettier

      - name: Install yapf
        run: pip install yapf

      - name: Install buildifier
        run: |
          BUILDIFIER_VERSION=$(curl -s https://api.github.com/repos/bazelbuild/buildtools/releases/latest | grep 'tag_name' | cut -d '"' -f4)
          curl -L -o buildifier "https://github.com/bazelbuild/buildtools/releases/download/${BUILDIFIER_VERSION}/buildifier-linux-amd64"
          chmod +x buildifier
          sudo mv buildifier /usr/local/bin/

      - name: Configure git
        run: |
          git config --global user.name "CI"
          git config --global user.email "ci@example.com"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Fail if `go mod tidy` changes anything
        run: go mod tidy --diff
